Jdc user addr
nss-evening-cohort-14/SweetTooth pull request #31
Opened 2021-10-21 02:49 UTC by jim-conner

## Description
-added repo, controller, and model for UserAddress
- Address calls--> getbyId, getAll, Add 

## Related Issue

#2 #13 #10

## Motivation and Context

User needs an address for orders

## How Can This Be Tested?

git fetch origin jdc-user-addr

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

2021-10-23 14:18 UTC, Gabrielle-Tobermann approved these changes

2021-10-23 17:24 UTC, GonzalesMatthew requested changes
please included logic for State to be two capitalized characters to represent State abbreviations

2021-10-23 20:23 UTC, jimguistical commented
Added validation to UserAddress.State with regex

2021-10-25 01:48 UTC, GonzalesMatthew approved these changes

2021-10-25 01:48 UTC, merged